logo: "/images/profile.jpeg?raw=true" <br><br> #photo
title: Mario Sato # your name 
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  English/Japanese/Portuguese(BR)
  <br><br>
  Graduate Student in Computer Science
  University of Tsukuba 
  <br><br>
  Undergraduate in Business Administration
  INSPER - Instituto de Ensino e Pesquisa
  <br><br>
  contact: mariotsato.wb@gmail.com
  <br><br>
  <a href="https://www.linkedin.com/in/mariots/">View My LinkedIn Profile</a> 

  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
